import { Geist, Geist_Mono } from "next/font/google";
// import Sidebar from "../Components/Sidebar"; // Importera Sidebar
import "./globals.css";
import { Box } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Lägg till viewport meta-taggen här */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Box sx={{ display: "flex" }}>
          {/* Sidomeny */}
          {/* <Sidebar /> */}

          {/* Huvudinnehåll */}
          <Box sx={{ flexGrow: 1, padding: "20px" }}>
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}